# Generated by Django 4.1.7 on 2024-01-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('owner_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=250)),
                ('owner_pass', models.CharField(max_length=250)),
                ('owner_address', models.CharField(max_length=250, null=True)),
                ('owner_tel', models.CharField(max_length=250, null=True)),
                ('owner_email', models.CharField(max_length=250, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
